### ISSUE TITLE
Small problem | Video output is just one black screen

### ISSUE THREAD

**Issue by mariobranco** [TaPO4eg3D/discord-monitors-to-vc#14]
OS: ubuntu 20.04 

I did make sure that i have asciimatics and v4l2 install with this:
sudo pip install asciimatics
sudo apt install v4l2loopback-dkms

Restart the Discord and i go on the discord settings and select CAMERA: VirtualScreen...
But i just got a black screen.
Is there some problem with this script running on python3 ?

**Comment by lefigueiredo** [comment]
I had the same problem, but i figured it out. You must maintain the terminal opened while you want to use it!
Once you close the terminal, the screen is black again.

**Comment by mariobranco** [comment]
I have black screen with the terminal open.

**Comment by TaPO4eg3D** [comment]
Sorry for a long time with no answer. Currently, I'm done with maintaining this project since Discord can be used with the system-wide installed Electron. Recent versions of Electron contain fixes for Linux screen sharing

You can read this PKGBUILD to figure out how to do it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord_arch_electron

or this one: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=discord-canary-electron-bin
